version: '3'
services:
  web:
    image: react-app-image
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  # You can define more services like database, cache, etc.
